name: Update Wheel Definitions
on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering
jobs:
  update-nautilus-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Nautilus wheel generator
        id: generate_wheels
        run: |
          nix run .#generate-wheels
      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are any changes in the nix directory
          if git diff --quiet HEAD -- nix/; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in nix/ directory"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in nix/ directory"
            
            # Count changed files and store for PR body
            changed_files=$(git diff --name-only HEAD -- nix/ | wc -l)
            echo "changed-files=$changed_files" >> $GITHUB_OUTPUT
            
            echo "Changed files:"
            git diff --name-only HEAD -- nix/
          fi
      - name: Get current UTC timestamp
        id: ts
        run: echo "now=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Nautilus Trader wheel definitions"
          title: "Update Nautilus Trader wheel definitions"
          body: |
            🤖 **Automated update of Nautilus Trader wheel definitions**

            This pull request contains automatically generated updates to the Nix expressions for Nautilus Trader Python wheels.

            ### Changes
            - Updated wheel definitions in `nix/nautilus/` directory
            - Generated from the latest packages available at https://packages.nautechsystems.io/simple/
            - Generated **${{ steps.generate_wheels.outputs.package-count }}** package derivations
            - Modified **${{ steps.check_changes.outputs.changed-files }}** Nix file(s)

            ### Package Summary
            **Platforms:** ${{ steps.generate_wheels.outputs.platforms }}  
            **Python Versions:** ${{ steps.generate_wheels.outputs.python-versions }}

            ### Generated Packages

            ${{ steps.generate_wheels.outputs.package-table }}

            ### Review Notes
            - This is an automated update
            - Please verify the generated expressions are correct
            - Check that the wheel URLs and hashes are valid
            - SHA256 hashes are truncated in the table above for readability

            **Generated on:** ${{ github.run_id }}  
            **Timestamp:** ${{ steps.ts.outputs.now }}
          branch: update-nautilus-wheels
          delete-branch: true
          labels: |
            automated
            dependencies
            nix
      - name: Output result
        run: |
          if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
            echo "✅ Pull request created with Nautilus wheel updates"
          else
            echo "ℹ️ No updates needed - wheel definitions are up to date"
          fi
